
FROM golang:1.12

WORKDIR github.com/Maftrek/redis-test/

COPY . github.com/Maftrek/redis-test/

WORKDIR github.com/Maftrek/redis-test/

RUN CGO_ENABLED=0 go build -o file

CMD ["./file", "getErrors"]