version: "2"

services:
  version1:
    build:
      context: .
      dockerfile: DockerFile.main
    volumes:
      - .:/github.com/Maftrek/redis-test
    links:
      - redis
  version2:
    build:
      context: .
      dockerfile: DockerFile.main
    volumes:
      - .:/github.com/Maftrek/redis-test
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

