version: "2"

services:
  version1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/redis-test
    links:
      - redis
  version2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/redis-test
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

