version: "2"

services:
  v12:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/redis-test
    links:
      - redis
  v22:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/redis-test
    links:
      - redis
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

